Controllers/AdoptarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EncuentraAtuMascota.Models;


namespace EncuentraAtuMascota.Controllers
{
    public class AdoptarController : Controller
    {
        private readonly EncuentraAtuMascotaContext _context;

        public AdoptarController(EncuentraAtuMascotaContext context)
        {
            _context = context;
        }

        // Obtener Lista de Solicitudes de Adopción
        public async Task<IActionResult> Administrar()
        {
            return View(await _context.Adoptar.ToListAsync());
        }

        // Muestra información Solicitudes de adopción (adoptantes)
        public async Task<IActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adoptar = await _context.Adoptar
                .FirstOrDefaultAsync(m => m.Id == id);
            if (adoptar == null)
            {
                return NotFound();
            }

            return View(adoptar);
        }

        // Crear nueva solicitud de Adopción
        public IActionResult Crear()
        {
            return View();
        }

        //Graba nueva solicitud de Adopción
        [HttpPost]
        public async Task<IActionResult> Crear([Bind("Id,NombreAdoptante,Telefono,Email,Direccion,Comentarios,FotoMascota")] Adoptar adoptar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(adoptar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Administrar));
            }
            return View(adoptar);
        }

        // Modifica información de solicitud de Adopción
        public async Task<IActionResult> Modificar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adoptar = await _context.Adoptar.FindAsync(id);
            if (adoptar == null)
            {
                return NotFound();
            }
            return View(adoptar);
        }

        // Graba datos modificados de la solicitud de adopción
        [HttpPost]
        public async Task<IActionResult> Modificar(int id, [Bind("Id,NombreAdoptante,Telefono,Email,Direccion,Comentarios,FotoMascota")] Adoptar adoptar)
        {
            if (id != adoptar.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(adoptar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdoptarExists(adoptar.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Administrar));
            }
            return View(adoptar);
        }

        // Eliminar solcitudes de adopción
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var adoptar = await _context.Adoptar
                .FirstOrDefaultAsync(m => m.Id == id);
            if (adoptar == null)
            {
                return NotFound();
            }
            return View(adoptar);
        }

        // Eliminar solicitud de adopción de la BD
        [HttpPost, ActionName("Eliminar")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var adoptar = await _context.Adoptar.FindAsync(id);
            _context.Adoptar.Remove(adoptar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Administrar));
        }

        // Busca el Id de la Mascota que debe usar
        private bool AdoptarExists(int id)
        {
            return _context.Adoptar.Any(e => e.Id == id);
        }
    }
}

Controllers/MiMascotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EncuentraAtuMascota.Models;

namespace EncuentraAtuMascota.Controllers
{
    public class MiMascotaController : Controller
    {
        private readonly EncuentraAtuMascotaContext _context;

        public MiMascotaController(EncuentraAtuMascotaContext context)
        {
            _context = context;
        }

        //Obtener Mis Mascotas - Lista
        public async Task<IActionResult> Administrar()
        {
            return View(await _context.MiMascota.ToListAsync());
        }

        //Muestra información de la Mascota
        public async Task<IActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var miMascota = await _context.MiMascota
                .FirstOrDefaultAsync(m => m.Id == id);
            if (miMascota == null)
            {
                return NotFound();
            }

            return View(miMascota);
        }

        //Creara nueva Mascota
        public IActionResult Crear()
        {
            return View();
        }

        //Graba información de nueva mascota en la BD
        [HttpPost]

        public async Task<IActionResult> Crear([Bind("Id,Nombre,Edad,Tamaño,Sexo,Raza,Descripcion,NombreDueno,Telefono,FotoMascota")] MiMascota miMascota)
        {
            if (ModelState.IsValid)
            {
                _context.Add(miMascota);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Administrar));
            }
            return View(miMascota);
        }

        //Modificar información de la Mascota
        public async Task<IActionResult> Modificar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var miMascota = await _context.MiMascota.FindAsync(id);
            if (miMascota == null)
            {
                return NotFound();
            }
            return View(miMascota);
        }

        //Graba datos modificados de la Mascota
        [HttpPost]
        public async Task<IActionResult> Modificar(int id, [Bind("Id,Nombre,Edad,Tamaño,Sexo,Raza,Descripcion,NombreDueno,Telefono,FotoMascota")] MiMascota miMascota)
        {
            if (id != miMascota.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(miMascota);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MiMascotaExists(miMascota.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Administrar));
            }
            return View(miMascota);
        }

        // Eliminar Mascotas
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var miMascota = await _context.MiMascota
                .FirstOrDefaultAsync(m => m.Id == id);
            if (miMascota == null)
            {
                return NotFound();
            }

            return View(miMascota);
        }

        ///Elimina Mascota de la BD
        [HttpPost, ActionName("Eliminar")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var miMascota = await _context.MiMascota.FindAsync(id);
            _context.MiMascota.Remove(miMascota);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Administrar));
        }

        private bool MiMascotaExists(int id)
        {
            return _context.MiMascota.Any(e => e.Id == id);
        }
    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EncuentraAtuMascota.Models;

namespace EncuentraAtuMascota.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly EncuentraAtuMascotaContext _context;

        public UsuariosController(EncuentraAtuMascotaContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Administrar()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }

        // GET: Usuarios/Crear
        public IActionResult Crear()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombres,Apellidos,Sexo,Email,Telefono,FechaNacimiento,Direccion,Usuario,Clave")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuarios);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Administrar));
            }
            return View(usuarios);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuarios.FindAsync(id);
            if (usuarios == null)
            {
                return NotFound();
            }
            return View(usuarios);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombres,Apellidos,Sexo,Email,Telefono,FechaNacimiento,Direccion,Usuario,Clave")] Usuarios usuarios)
        {
            if (id != usuarios.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuarios);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuariosExists(usuarios.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Administrar));
            }
            return View(usuarios);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarios = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuarios == null)
            {
                return NotFound();
            }

            return View(usuarios);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuarios = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuarios);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Administrar));
        }

        private bool UsuariosExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EncuentraAtuMascota</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EncuentraAtuMascota</a>*@

                <img src="~/images/Captura.PNG" class="navbar-brand" height="160" width="80"/>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Adoptar" asp-action="Administrar">Adoptar</a></li>
                    <li><a asp-area="" asp-controller="MiMascota" asp-action="Administrar">Mi Mascota</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contactanos">Contáctanos</a></li>
                    <li><a asp-area="" asp-controller="Usuarios" asp-action="Crear">Nuevo Usuario</a></li>
                    <li><a asp-area="" asp-controller="Usuarios" asp-action="Administrar">Administrar</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Home" asp-action="IniciarSesion">
                        <span class="glyphicon glyphicon-user"></span> Iniciar Sesión</a></li>
                    <li><a href="#">
                        <span class="glyphicon glyphicon-log-in"></span> Salir</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - EncuentraAtuMascota</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>